#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/chromium-browser/default -- "$@"
dpkg-maintscript-helper rm_conffile /etc/chromium-browser/customizations/00-example -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/12.10ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
